issuer: https://token.actions.githubusercontent.com
subject: repo:erikgb/octo-sts-testing:ref:refs/heads/main

permissions:
  contents: write
  issues: write
  statuses: write
  pull_requests: write
  workflows: write
