name: Renovate
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: '0/15 * * * *'

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest

    if: github.repository == 'erikgb/octo-sts-testing'

    permissions:
      contents: read
      id-token: write # Needed to federate tokens.

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Octo STS Token Exchange
        uses: octo-sts/action@e480437973a6f6ac2e9caa40ecabedc870d76395 # main
        id: octo-sts
        with:
          scope: erikgb/octo-sts-testing
          identity: renovate

      - name: Run Self-hosted Renovate
        uses: renovatebot/github-action@b11417b9eaac3145fe9a8544cee66503724e32b6 # v43.0.8
        with:
          configurationFile: .github/renovate.json5
          token: ${{ steps.octo-sts.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          RENOVATE_ONBOARDING: "false"
          RENOVATE_PLATFORM: "github"
          LOG_LEVEL: "debug"
